spring.application.name=hyperroute
spring.datasource.url=jdbc:postgresql://localhost:5432/hyper_route_dev
spring.datasource.username=postgres
spring.datasource.password=geeth123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect