spring.application.name=hyperroute
spring.datasource.url=jdbc:postgresql://localhost:5432/hyper_route_dev
spring.datasource.username=postgres
spring.datasource.password=geeth123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

# Configure the Kafka Producer to serialize keys as Strings and values as JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Configure the Kafka Consumer to deserialize values back into objects safely
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Allows the consumer to trust payloads originating from your application packages
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hyperroute.hyperroute.*

# Prints the SQL queries to the console
#spring.jpa.show-sql=true

# Formats the SQL so it's readable instead of one giant line
#spring.jpa.properties.hibernate.format_sql=true

# Optional: Shows the actual values bound to the parameters (like UUIDs or text)
#logging.level.org.hibernate.orm.jdbc.bind=trace

# CRITICAL: Ensures Hibernate actually tries to create/update tables on startup
spring.jpa.hibernate.ddl-auto=update