spring.application.name=hyperroute
spring.datasource.url=jdbc:postgresql://localhost:5432/hyper_route_dev
spring.datasource.username=postgres
spring.datasource.password=geeth123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Prints the SQL queries to the console
spring.jpa.show-sql=true

# Formats the SQL so it's readable instead of one giant line
spring.jpa.properties.hibernate.format_sql=true

# Optional: Shows the actual values bound to the parameters (like UUIDs or text)
logging.level.org.hibernate.orm.jdbc.bind=trace

# CRITICAL: Ensures Hibernate actually tries to create/update tables on startup
spring.jpa.hibernate.ddl-auto=update